name: Deploy Angular App with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Build Angular App
      run: npm run build --prod

    - name: Build Docker Image
      run: docker build -t test-app-docker-image .

    - name: Push to Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker tag test-app-docker-image ${{ secrets.DOCKER_USERNAME }}/test-app-docker-image
        docker push ${{ secrets.DOCKER_USERNAME }}/test-app-docker-image