name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          export_default_credentials: true

      - name: Build Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/test-app:latest .
          docker push gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/test-app:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy test-app \
            --image gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/test-app:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
